### ISSUE TITLE
[bug]chat-app, todo-listのフォルダがgitに取り込まれない問題

### ISSUE THREAD

**Issue by kurosiba** [kuriken121227/chatApp#2]
front環境で作成した資材がgitにファイルとしてご認識されるバグの対処

次回は以下の通りに対処する
1. 取り込まれないフォルダをカレントにしてgit addを実行する
2. 一番上のフォルダに移動して再度add⇒commit⇒pushを行う

**Comment by 4Leaf-0428** [comment]
kurisu02の中身全部を新規フォルダに入れたらchat-app動かせます
